#!/bin/bash
if [ ! -e /content/models ]; then
        mkdir -p /root/.torch/models
        mkdir -p /root/.fastai/data
        ln -s /root/.torch/models /content
        ln -s /root/.fastai/data /content
        rm -rf /content/sample_data/
fi

echo Updating fastai...
pip install fastai --upgrade > /dev/null

echo Downloading OpenCV4...
curl -sL https://storage.googleapis.com/opencv4/opencv4.tgz | tar zxf - -C / \
  && ldconfig /opt/opencv4/lib/ \
  && rm -f /usr/lib/pkgconfig/opencv4.pc \
  && ln -s /opt/opencv4/lib/pkgconfig/opencv4.pc /usr/lib/pkgconfig/opencv4.pc

echo Done.
