#!/bin/bash
set -e
# create symlinks if not existing
[ ! -L "/home/ec2-user/.torch" ] && ln -s /home/ec2-user/SageMaker/.torch /home/ec2-user/.torch
[ ! -L "/home/ec2-user/.fastai" ] && ln -s /home/ec2-user/SageMaker/.fastai /home/ec2-user/.fastai

# update the fastai library
if [ -f "/home/ec2-user/.fastai/create_complete" ]; then
    echo "Updating fastai environment"
    cd /home/ec2-user/SageMaker
    # update the fastai library
    source activate envs/fastai
    conda update -yq fastai
    # install the ipython kernel
    ipython kernel install --name 'fastai' --display-name 'Python 3' --user

    # run the custom script
    ./custom-start-script.sh
else
    echo "Still running create script..Exiting"
fi
echo "Finished running onStart script"