/*
THIS FILE WAS AUTOGENERATED! DO NOT EDIT!
file to edit: /home/ubuntu/fastai_docs/dev_swift/02_fully_connected.ipynb/lastPathComponent

*/
        
import Path
import TensorFlow


// Typing Tensor<Float> all the time is tedious.  The S4TF team expects to 
// make "Float" be the default so we can just say "Tensor".  Until that happens
// though, we can define our own alias.
public typealias TF=Tensor<Float>

public func normalize(_ x:TF, mean:TF, std:TF) -> TF {
    return (x-mean)/std
}

public func testNearZero(_ a: TF, tolerance: Float = 1e-3) {
    assert(abs(a) < tolerance, "Near zero: \(a)")
}

public func mse(_ out: TF, _ targ: TF) -> TF {
    return (out.squeezingShape(at: -1) - targ).squared().mean()
}
